FROM franciscotobar/rskj:optimism-6.1.0

# COPY rskj.logback.xml /etc/rsk/logback.xml
# COPY rskj.node.conf /etc/rsk/node.conf
# COPY rskj.genesis.json /var/lib/rsk/rsk-dev.json
# COPY ./entrypoint-l1.sh /entrypoint.sh

VOLUME ["/db"]

CMD ["--regtest", "--reset"]

# ENTRYPOINT ["/bin/sh", "/entrypoint.sh"]
